#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
#spring.datasource.url=jdbc:mysql://localhost:3306/project_database?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=coderslab
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.generate-ddl=true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/project_database?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true